authors = [
  { name = "Chandler Shortlidge", email = "chandlershortlidge@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.0",
    "python-dotenv>=1.0.0",
]

[project.optional-dependencies]
dev = ["ruff"]
