[project]
name = "baby_timer_app"
version = "0.1.0"
description = "A simple timer to help parents track their baby's sleep schedule."
authors = [
  { name = "Chandler Shortlidge", email = "chandlershortlidge@gmail.com" }
]
dependencies = [
    "flask>=3.1.1",
    "ruff>=0.12.9"
]